from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

lang = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🇷🇺',callback_data='RU')
btn2 = InlineKeyboardButton(text='🇺🇸',callback_data='ENG')
btn3 = InlineKeyboardButton(text='🇹🇷',callback_data='TUR')
lang.insert(btn1)
lang.insert(btn2)
lang.insert(btn3)

menu_ru = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🌿 Ассортимент 🌿',callback_data='menu_1_ru')
btn2 = InlineKeyboardButton(text='📝️ Отзывы 📝',callback_data='menu_2_ru')
btn3 = InlineKeyboardButton(text='🔐 Гарант 🔐',callback_data='menu_3_ru')
btn4 = InlineKeyboardButton(text='📨 Вкл/Выкл на рассылку 📨',callback_data='mailing_ru')
btn5 = InlineKeyboardButton(text='📪️ Заказать доставку на дату и время 📪',callback_data='excursion_mount')
btn6 = InlineKeyboardButton(text='👨‍💼 Поддержка 👨',callback_data='menu_4_ru')
btn7 = InlineKeyboardButton(text='❓ FAQ ❓',callback_data='menu_5_ru')
btn8 = InlineKeyboardButton(text='🏳 Назад к выбору языка 🏴',callback_data='back_to_lang')
menu_ru.insert(btn1)
menu_ru.insert(btn2)
menu_ru.insert(btn3)
menu_ru.insert(btn4)
menu_ru.insert(btn5)
menu_ru.insert(btn6)
menu_ru.insert(btn7)
menu_ru.insert(btn8)

menu_eng = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🌿 Assortment 🌿',callback_data='menu_1_eng')
btn2 = InlineKeyboardButton(text='📝️ Reviews 📝',callback_data='menu_2_eng')
btn3 = InlineKeyboardButton(text='🔐 Guarantee 🔐',callback_data='menu_3_eng')
btn4 = InlineKeyboardButton(text='📨 On/Off for mailing 📨',callback_data='mailing_eng')
btn5 = InlineKeyboardButton(text='📪️ Order delivery on date and time 📪',callback_data='excursion_mount')
btn6 = InlineKeyboardButton(text='👨‍💼 Support 👨',callback_data='menu_4_eng')
btn7 = InlineKeyboardButton(text='❓ FAQ ❓',callback_data='menu_5_eng')
btn8 = InlineKeyboardButton(text='🏳 Back to language selection 🏴',callback_data='back_to_lang')
menu_eng.insert(btn1)
menu_eng.insert(btn2)
menu_eng.insert(btn3)
menu_eng.insert(btn4)
menu_eng.insert(btn5)
menu_eng.insert(btn6)
menu_eng.insert(btn7)
menu_eng.insert(btn8)

menu_tur = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🌿 Çeşitler 🌿',callback_data='menu_1_tur')
btn2 = InlineKeyboardButton(text='📝️ Yorumlar 📝',callback_data='menu_2_tur')
btn3 = InlineKeyboardButton(text='🔐 Garanti 🔐',callback_data='menu_3_tur')
btn4 = InlineKeyboardButton(text='📨 Postalama için Açık/Kapalı 📨',callback_data='mailing')
btn5 = InlineKeyboardButton(text='📪️ Tarih ve saatte teslimat siparişi verin 📪',callback_data='excursion_mount')
btn6 = InlineKeyboardButton(text='👨‍💼 Destek 👨',callback_data='menu_4_tur')
btn7 = InlineKeyboardButton(text='❓ FAQ ❓',callback_data='menu_5_tur')
btn8 = InlineKeyboardButton(text='🏳 Dil seçimine geri dön 🏴',callback_data='back_to_lang')
menu_tur.insert(btn1)
menu_tur.insert(btn2)
menu_tur.insert(btn3)
menu_tur.insert(btn4)
menu_tur.insert(btn5)
menu_tur.insert(btn6)
menu_tur.insert(btn7)
menu_tur.insert(btn8)


back_ru = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu_ru')
back_ru.insert(btn1)

back_eng = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='◀️ Back to menu',callback_data='back_to_menu_eng')
back_eng.insert(btn1)

back_tur = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='◀️ Menüye geri dön',callback_data='back_to_menu_tur')
back_tur.insert(btn1)

cancel = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Отмена',callback_data='cancel')
cancel.insert(btn1)


mailing_ru = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Включить\выключить рассылку',callback_data='off_on_mailing_ru')
btn2 = InlineKeyboardButton(text='Вернуть назад',callback_data='back_to_menu_ru')
mailing_ru.insert(btn1)
mailing_ru.insert(btn2)

mailing_eng = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Enable/disable newsletter',callback_data='off_on_mailing_eng')
btn2 = InlineKeyboardButton(text='Return back',callback_data='back_to_menu_eng')
mailing_eng.insert(btn1)
mailing_eng.insert(btn2)

mailing_tur = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Bülteni etkinleştirme/devre dışı bırakma',callback_data='off_on_mailing_tur')
btn2 = InlineKeyboardButton(text='Geri dön',callback_data='back_to_menu_tur')
mailing_tur.insert(btn1)
mailing_tur.insert(btn2)

calendar = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='1',callback_data='1')
btn2 = InlineKeyboardButton(text='2',callback_data='2')
btn3 = InlineKeyboardButton(text='3',callback_data='3')
btn4 = InlineKeyboardButton(text='4',callback_data='4')
btn5 = InlineKeyboardButton(text='5',callback_data='5')
btn6 = InlineKeyboardButton(text='6',callback_data='6')
btn7 = InlineKeyboardButton(text='7',callback_data='7')
btn8 = InlineKeyboardButton(text='8',callback_data='8')
btn9 = InlineKeyboardButton(text='9',callback_data='9')
btn10 = InlineKeyboardButton(text='10',callback_data='10')
btn11 = InlineKeyboardButton(text='11',callback_data='11')
btn12 = InlineKeyboardButton(text='12',callback_data='12')
btn13 = InlineKeyboardButton(text='13',callback_data='13')
btn14 = InlineKeyboardButton(text='14',callback_data='14')
btn15 = InlineKeyboardButton(text='15',callback_data='15')
btn16 = InlineKeyboardButton(text='16',callback_data='16')
btn17 = InlineKeyboardButton(text='17',callback_data='17')
btn18 = InlineKeyboardButton(text='18',callback_data='18')
btn19 = InlineKeyboardButton(text='19',callback_data='19')
btn20 = InlineKeyboardButton(text='20',callback_data='20')
btn21 = InlineKeyboardButton(text='21',callback_data='21')
btn22 = InlineKeyboardButton(text='22',callback_data='22')
btn23 = InlineKeyboardButton(text='23',callback_data='23')
btn24 = InlineKeyboardButton(text='24',callback_data='24')
btn25 = InlineKeyboardButton(text='25',callback_data='25')
btn26 = InlineKeyboardButton(text='26',callback_data='26')
btn27 = InlineKeyboardButton(text='27',callback_data='27')
btn28 = InlineKeyboardButton(text='28',callback_data='28')

calendar.insert(btn1)
calendar.insert(btn2)
calendar.insert(btn3)
calendar.insert(btn4)
calendar.insert(btn5)
calendar.insert(btn6)
calendar.insert(btn7)
calendar.insert(btn8)
calendar.insert(btn9)
calendar.insert(btn10)
calendar.insert(btn11)
calendar.insert(btn12)
calendar.insert(btn13)
calendar.insert(btn14)
calendar.insert(btn15)
calendar.insert(btn16)
calendar.insert(btn17)
calendar.insert(btn18)
calendar.insert(btn19)
calendar.insert(btn20)
calendar.insert(btn21)
calendar.insert(btn22)
calendar.insert(btn23)
calendar.insert(btn24)
calendar.insert(btn25)
calendar.insert(btn26)
calendar.insert(btn27)
calendar.insert(btn28)



mount = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='January',callback_data='jan')
btn2 = InlineKeyboardButton(text='February',callback_data='feb')
btn3 = InlineKeyboardButton(text='March',callback_data='mar')
btn4 = InlineKeyboardButton(text='April',callback_data='apr')
btn5 = InlineKeyboardButton(text='May',callback_data='mai')
btn6 = InlineKeyboardButton(text='June',callback_data='iun')
btn7 = InlineKeyboardButton(text='Июль',callback_data='iul')
btn8 = InlineKeyboardButton(text='August',callback_data='avg')
btn9 = InlineKeyboardButton(text='September',callback_data='sent')
btn10 = InlineKeyboardButton(text='October',callback_data='okt')
btn11 = InlineKeyboardButton(text='November',callback_data='noyab')
btn12 = InlineKeyboardButton(text='December',callback_data='dec')
mount.insert(btn1)
mount.insert(btn2)
mount.insert(btn3)
mount.insert(btn4)
mount.insert(btn5)
mount.insert(btn6)
mount.insert(btn7)
mount.insert(btn8)
mount.insert(btn9)
mount.insert(btn10)
mount.insert(btn11)
mount.insert(btn12)


time = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='10:00',callback_data='10:00')
btn2 = InlineKeyboardButton(text='11:00',callback_data='11:00')
btn3 = InlineKeyboardButton(text='12:00',callback_data='12:00')
btn4 = InlineKeyboardButton(text='13:00',callback_data='13:00')
btn5 = InlineKeyboardButton(text='14:00',callback_data='14:00')
btn6 = InlineKeyboardButton(text='15:00',callback_data='15:00')
btn7 = InlineKeyboardButton(text='16:00',callback_data='16:00')
btn8 = InlineKeyboardButton(text='17:00',callback_data='17:00')

time.insert(btn1)
time.insert(btn2)
time.insert(btn3)
time.insert(btn4)
time.insert(btn5)
time.insert(btn6)
time.insert(btn7)
time.insert(btn8)

