from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📄 Подать заявление',callback_data='menu_1')
btn2 = InlineKeyboardButton(text='⚖️ Права клиента',callback_data='menu_2')
btn3 = InlineKeyboardButton(text='🏛 Гос. помощь по программе',callback_data='menu_3')
btn4 = InlineKeyboardButton(text='📨 Вкл/Выкл на рассылку',callback_data='mailing')
#btn5 = InlineKeyboardButton(text='☎️ Записаться на консультацию',callback_data='excursion_mount')
btn6 = InlineKeyboardButton(text='👨‍💼 Поддержка',callback_data='menu_4')
btn7 = InlineKeyboardButton(text='❓ FAQ',callback_data='menu_5')
menu.insert(btn1)
menu.insert(btn2)
menu.insert(btn3)
menu.insert(btn4)
#menu.insert(btn5)
menu.insert(btn6)
menu.insert(btn7)

menu_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📥 На возврат средств',callback_data='menu_2_1')
btn2 = InlineKeyboardButton(text='📄 На обжалование решения',callback_data='menu_2_2')
btn3 = InlineKeyboardButton(text='💬 На консультирование',callback_data='menu_2_3')
btn4 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
menu_2.insert(btn1)
menu_2.insert(btn2)
menu_2.insert(btn3)
menu_2.insert(btn4)

menu_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🔎 Критерии участия',callback_data='menu_3_1')
btn2 = InlineKeyboardButton(text='📑 Список документов',callback_data='menu_3_2')
btn3 = InlineKeyboardButton(text='❓ Часто задаваемые вопросы',callback_data='menu_3_3')
btn4 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
menu_3.insert(btn1)
menu_3.insert(btn2)
menu_3.insert(btn3)
menu_3.insert(btn4)

back = InlineKeyboardMarkup(row_width=1)
btn2 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu')
back.insert(btn1)

cancel = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Отмена',callback_data='cancel')
cancel.insert(btn1)


mailing = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Включить\выключить рассылку',callback_data='off_on_mailing')
btn2 = InlineKeyboardButton(text='Вернуть назад',callback_data='back_to_menu')
mailing.insert(btn1)
mailing.insert(btn2)

calendar = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='1',callback_data='1')
btn2 = InlineKeyboardButton(text='2',callback_data='2')
btn3 = InlineKeyboardButton(text='3',callback_data='3')
btn4 = InlineKeyboardButton(text='4',callback_data='4')
btn5 = InlineKeyboardButton(text='5',callback_data='5')
btn6 = InlineKeyboardButton(text='6',callback_data='6')
btn7 = InlineKeyboardButton(text='7',callback_data='7')
btn8 = InlineKeyboardButton(text='8',callback_data='8')
btn9 = InlineKeyboardButton(text='9',callback_data='9')
btn10 = InlineKeyboardButton(text='10',callback_data='10')
btn11 = InlineKeyboardButton(text='11',callback_data='11')
btn12 = InlineKeyboardButton(text='12',callback_data='12')
btn13 = InlineKeyboardButton(text='13',callback_data='13')
btn14 = InlineKeyboardButton(text='14',callback_data='14')
btn15 = InlineKeyboardButton(text='15',callback_data='15')
btn16 = InlineKeyboardButton(text='16',callback_data='16')
btn17 = InlineKeyboardButton(text='17',callback_data='17')
btn18 = InlineKeyboardButton(text='18',callback_data='18')
btn19 = InlineKeyboardButton(text='19',callback_data='19')
btn20 = InlineKeyboardButton(text='20',callback_data='20')
btn21 = InlineKeyboardButton(text='21',callback_data='21')
btn22 = InlineKeyboardButton(text='22',callback_data='22')
btn23 = InlineKeyboardButton(text='23',callback_data='23')
btn24 = InlineKeyboardButton(text='24',callback_data='24')
btn25 = InlineKeyboardButton(text='25',callback_data='25')
btn26 = InlineKeyboardButton(text='26',callback_data='26')
btn27 = InlineKeyboardButton(text='27',callback_data='27')
btn28 = InlineKeyboardButton(text='28',callback_data='28')
btn29 = InlineKeyboardButton(text='Назад в меню',callback_data='back_to_menu')
calendar.insert(btn1)
calendar.insert(btn2)
calendar.insert(btn3)
calendar.insert(btn4)
calendar.insert(btn5)
calendar.insert(btn6)
calendar.insert(btn7)
calendar.insert(btn8)
calendar.insert(btn9)
calendar.insert(btn10)
calendar.insert(btn11)
calendar.insert(btn12)
calendar.insert(btn13)
calendar.insert(btn14)
calendar.insert(btn15)
calendar.insert(btn16)
calendar.insert(btn17)
calendar.insert(btn18)
calendar.insert(btn19)
calendar.insert(btn20)
calendar.insert(btn21)
calendar.insert(btn22)
calendar.insert(btn23)
calendar.insert(btn24)
calendar.insert(btn25)
calendar.insert(btn26)
calendar.insert(btn27)
calendar.insert(btn28)
calendar.insert(btn29)


mount = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Январь',callback_data='jan')
btn2 = InlineKeyboardButton(text='Февраль',callback_data='feb')
btn3 = InlineKeyboardButton(text='Март',callback_data='mar')
btn4 = InlineKeyboardButton(text='Апрель',callback_data='apr')
btn5 = InlineKeyboardButton(text='Май',callback_data='mai')
btn6 = InlineKeyboardButton(text='Июнь',callback_data='iun')
btn7 = InlineKeyboardButton(text='Июль',callback_data='iul')
btn8 = InlineKeyboardButton(text='Август',callback_data='avg')
btn9 = InlineKeyboardButton(text='Сентябрь',callback_data='sent')
btn10 = InlineKeyboardButton(text='Октябрь',callback_data='okt')
btn11 = InlineKeyboardButton(text='Ноябрь',callback_data='noyab')
btn12 = InlineKeyboardButton(text='Декабрь',callback_data='dec')
btn13 = InlineKeyboardButton(text='Назад к меню',callback_data='back_to_menu')
mount.insert(btn1)
mount.insert(btn2)
mount.insert(btn3)
mount.insert(btn4)
mount.insert(btn5)
mount.insert(btn6)
mount.insert(btn7)
mount.insert(btn8)
mount.insert(btn9)
mount.insert(btn10)
mount.insert(btn11)
mount.insert(btn12)
mount.insert(btn13)

time = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='10:00',callback_data='10:00')
btn2 = InlineKeyboardButton(text='11:00',callback_data='11:00')
btn3 = InlineKeyboardButton(text='12:00',callback_data='12:00')
btn4 = InlineKeyboardButton(text='13:00',callback_data='13:00')
btn5 = InlineKeyboardButton(text='14:00',callback_data='14:00')
btn6 = InlineKeyboardButton(text='15:00',callback_data='15:00')
btn7 = InlineKeyboardButton(text='16:00',callback_data='16:00')
btn8 = InlineKeyboardButton(text='17:00',callback_data='17:00')
btn9 = InlineKeyboardButton(text='Назад в меню',callback_data='back_to_menu')
time.insert(btn1)
time.insert(btn2)
time.insert(btn3)
time.insert(btn4)
time.insert(btn5)
time.insert(btn6)
time.insert(btn7)
time.insert(btn8)
time.insert(btn9)
